version: '3.4'
services:
  devcontainer:
    image: ghcr.io/RyzeNGrind/devcontainer-nix:main
    environment:
      USE_DIRENV: "true"
      CUSTOM_ENV_VAR: "value"
    volumes:
      - ./data:/data:rw